apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: java-maven-app-eks
  region: eu-west-2
  version: "1.29"
nodeGroups:
  - name: ng-java-maven-app
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
